version: '3.7'

services:
  fe2_monitoring:
    image: odin568/fe2_monitoring:latest
    container_name: fe2_monitoring
    restart: always
    environment:
      ## The defaults
      #- INITIALDELAY=10000
      #- FIXEDDELAY=60000
      #- ALIVE_CRON=0 0 6 * * *
      ## Adjust logging
      #- LOGGING_LEVEL_COM_ODIN568=DEBUG
      #- LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SCHEDULING=DEBUG
      - PUSHOVER_TOKEN=addTokenHere
      - PUSHOVER_USER=addUserHere
