name: Latest

on:
  push:
    branches: [ main ]

jobs:
  docker_buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate version
        run: echo "RELEASE_VERSION=latest" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up QEMU environment
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push all images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: BUILDX_QEMU_ENV=true
          tags: odin568/fe2_monitoring:${{ env.RELEASE_VERSION }}